name = "ConstrainedParameter"
uuid = "9b03a4ca-12fb-4bcb-bb73-21858dce4290"
authors = ["hongbinren <hongbinrenscu@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
